const IMAGES = {
  LOGO: "/assets/images/HomeAssets/logo.svg",
  LOGO_WHITE: "/assets/images/HomeAssets/logo-white.svg",
  LOGO_AFF: "/assets/images/AffiliateAssets/logo-aff.png",
  LOGO_AFF_WHITE: "/assets/images/AffiliateAssets/logo-aff-gr.svg",
  BG_HOME: "/assets/images/HomeAssets/world.svg",
  BG_HOME_AFF: "/assets/images/AffiliateAssets/world.svg",
  ICON1: "/assets/images/HomeAssets/icon1.svg",
  ICON2: "/assets/images/HomeAssets/icon2.svg",
  ICON3: "/assets/images/HomeAssets/icon3.svg",
  ICON4: "/assets/images/HomeAssets/icon4.svg",
  ICON5: "/assets/images/HomeAssets/icon5.svg",
  ICON6: "/assets/images/HomeAssets/icon6.svg",
  ICON7: "/assets/images/HomeAssets/icon7.svg",
  ICON8: "/assets/images/HomeAssets/icon8.svg",
  ICON9: "/assets/images/HomeAssets/icon9.svg",
  ICON10: "/assets/images/HomeAssets/icon10.svg",
  ICON11: "/assets/images/HomeAssets/icon11.svg",
  ICON12: "/assets/images/HomeAssets/icon12.svg",
  SELLER: "/assets/images/HomeAssets/logo-seller.svg",
  AFFILIATE: "/assets/images/HomeAssets/logo-affiliate.svg",
  STARTSELLING: {
    DESKTOP: "/assets/images/HomeAssets/startsellingdesk.svg",
    MOBILE: "/assets/images/HomeAssets/startsellingmob.svg",
  },
  COUNTRIES: "/assets/images/HomeAssets/countries.png",
  PARTNER1: "/assets/images/HomeAssets/part1.png",
  PARTNER2: "/assets/images/HomeAssets/part2.png",
  PARTNER3: "/assets/images/HomeAssets/part3.png",
  PARTNER4: "/assets/images/HomeAssets/part4.png",
  PARTNER5: "/assets/images/HomeAssets/part5.png",
  PARTNER6: "/assets/images/HomeAssets/part6.png",
  PARTNER7: "/assets/images/HomeAssets/part7.png",
  SEEN1: "/assets/images/HomeAssets/seen1.svg",
  SEEN2: "/assets/images/HomeAssets/seen2.svg",
  SEEN3: "/assets/images/HomeAssets/seen3.svg",
  SEEN4: "/assets/images/HomeAssets/seen4.svg",
  SEEN5: "/assets/images/HomeAssets/seen5.png",
  AR: "/assets/images/AffiliateAssets/ar.png",
  EN: "/assets/images/AffiliateAssets/en.png",
  DASHBOARD: "/assets/images/AffiliateAssets/dashboard.jpeg",
  PLAY: "/assets/images/AffiliateAssets/play-icon.png",
  BG_FIX: {
    FIRST: "/assets/images/AffiliateAssets/bg-fix3.png",
    SECOND: "/assets/images/AffiliateAssets/bg-fix1.png",
    THIRD: "/assets/images/AffiliateAssets/bg-fix2.png",
    FOURTH: "/assets/images/AffiliateAssets/bg-fix4.svg",
    FIFTH: "/assets/images/AffiliateAssets/bg-fix6.svg",
  },
  ACCOUNT_MANAGER: "/assets/images/AffiliateAssets/AccountManager.png",
  ICON13: "/assets/images/AffiliateAssets/icon1.png",
  ICON14: "/assets/images/AffiliateAssets/icon2.png",
  ICON15: "/assets/images/AffiliateAssets/icon3.png",
  SEPCOUNTRIES: [
    "/assets/images/AffiliateAssets/c1.svg",
    "/assets/images/AffiliateAssets/c2.svg",
    "/assets/images/AffiliateAssets/c3.svg",
    "/assets/images/AffiliateAssets/c4.svg",
    "/assets/images/AffiliateAssets/c5.svg",
    "/assets/images/AffiliateAssets/c6.svg",
    "/assets/images/AffiliateAssets/c7.svg",
    "/assets/images/AffiliateAssets/c8.png",
    "/assets/images/AffiliateAssets/c9.png",
    "/assets/images/AffiliateAssets/c10.png",
    "/assets/images/AffiliateAssets/c11.png",
  ],
  PLATEFORMS: [
    "/assets/images/AffiliateAssets/plat1.svg",
    "/assets/images/AffiliateAssets/plat2.svg",
    "/assets/images/AffiliateAssets/plat3.svg",
    "/assets/images/AffiliateAssets/plat4.svg",
  ],
  TUTO: "/assets/images/AffiliateAssets/tuto.png",
};

export default IMAGES;
